#if MCPMacros

import MCPShared
import SwiftCompilerPlugin
import SwiftSyntax
import SwiftSyntaxBuilder
import SwiftSyntaxMacros

public struct ServerMacro: MemberMacro {
    public static func expansion(
        of node: AttributeSyntax,
        providingMembersOf declaration: some DeclGroupSyntax,
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {

        // Ensure this is applied to a struct
        guard let _ = declaration.as(StructDeclSyntax.self) else {
            throw MacroError.invalidDeclaration
        }

        // Extract macro arguments
        guard let arguments = node.arguments,
            case let .argumentList(argumentList) = arguments
        else {
            throw MacroError.invalidArguments
        }

        var serverName: String = ""
        var serverVersion: String = ""
        // var serverDescription: String? = ""
        var toolsArray: String = "[]"
        var promptsArray: String = "[]"
        var serverType: String = "stdio"
        var httpPort: Int = 8080

        // Parse the arguments
        for argument in argumentList {
            guard let label = argument.label?.text else { continue }

            switch label {
            case "name":
                if let stringLiteral = argument.expression.as(StringLiteralExprSyntax.self),
                    let segment = stringLiteral.segments.first?.as(StringSegmentSyntax.self)
                {
                    serverName = segment.content.text
                }
            case "version":
                if let stringLiteral = argument.expression.as(StringLiteralExprSyntax.self),
                    let segment = stringLiteral.segments.first?.as(StringSegmentSyntax.self)
                {
                    serverVersion = segment.content.text
                }
            case "tools":
                if let arrayExpr = argument.expression.as(ArrayExprSyntax.self) {
                    let elements = arrayExpr.elements.map { element in
                        element.expression.description.trimmingCharacters(in: .whitespacesAndNewlines)
                    }
                    toolsArray = "[\(elements.joined(separator: ", "))]"
                }
            case "prompts":
                if let arrayExpr = argument.expression.as(ArrayExprSyntax.self) {
                    let elements = arrayExpr.elements.map { element in
                        element.expression.description.trimmingCharacters(in: .whitespacesAndNewlines)
                    }
                    promptsArray = "[\(elements.joined(separator: ", "))]"
                }
            case "type":
                // Handle both .stdio and .http(port: Int) cases
                let expressionText = argument.expression.description.trimmingCharacters(in: .whitespacesAndNewlines)
                if expressionText == ".stdio" {
                    serverType = "stdio"
                } else if expressionText.hasPrefix(".http(") {
                    serverType = "http"
                    // Extract port number from .http(port: 3000) format
                    let portPattern = #/\.http\(port:\s*(\d+)\)/#
                    if let match = expressionText.firstMatch(of: portPattern) {
                        httpPort = Int(match.1) ?? 8080
                    }
                }
            default:
                break
            }
        }

        // Generate the appropriate transport and startup code based on server type
        let transportCode: String
        let startupCode: String

        if serverType == "stdio" {
            transportCode = ".stdio"
            startupCode = "try await server.startStdioServer()"
        } else {
            transportCode = ".http(port: \(httpPort))"
            startupCode = "try await server.startHttpServer()"
        }

        // Create a static main method that creates and starts the server
        let mainMethod: DeclSyntax = """
            public static func main() async throws {
                // Auto-generated by @Server macro
                try await MCPServer.withMCPServer(
                    name: "\(raw: serverName)",
                    version: "\(raw: serverVersion)",
                    transport: \(raw: transportCode),
                    tools: \(raw: toolsArray),
                    prompts: \(raw: promptsArray)
                ) { server in
                    \(raw: startupCode)
                }
            }
            """

        return [mainMethod]
    }
}

enum MacroError: Error, CustomStringConvertible {
    case invalidArguments
    case invalidDeclaration

    var description: String {
        switch self {
        case .invalidArguments:
            return "Invalid macro arguments"
        case .invalidDeclaration:
            return "Macro can only be applied to struct declarations"
        }
    }
}

#endif
